# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_select_input = QtWidgets.QPushButton(self.centralwidget)
        self.button_select_input.setGeometry(QtCore.QRect(20, 50, 181, 32))
        self.button_select_input.setObjectName("button_select_input")
        self.line_v = QtWidgets.QFrame(self.centralwidget)
        self.line_v.setGeometry(QtCore.QRect(210, -10, 31, 801))
        self.line_v.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_v.setObjectName("line_v")
        self.line_h = QtWidgets.QFrame(self.centralwidget)
        self.line_h.setGeometry(QtCore.QRect(230, 370, 601, 20))
        self.line_h.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h.setObjectName("line_h")
        self.video_player_original = VideoPlayer(self.centralwidget)
        self.video_player_original.setEnabled(True)
        self.video_player_original.setGeometry(QtCore.QRect(240, 10, 591, 361))
        self.video_player_original.setObjectName("video_player_original")
        self.video_player_result = VideoPlayer(self.centralwidget)
        self.video_player_result.setGeometry(QtCore.QRect(240, 390, 591, 361))
        self.video_player_result.setObjectName("video_player_result")
        self.input_min_length = QtWidgets.QSpinBox(self.centralwidget)
        self.input_min_length.setGeometry(QtCore.QRect(30, 130, 171, 24))
        self.input_min_length.setMaximum(10000)
        self.input_min_length.setProperty("value", 100)
        self.input_min_length.setObjectName("input_min_length")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line_h_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_h_2.setGeometry(QtCore.QRect(3, 30, 221, 20))
        self.line_h_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h_2.setObjectName("line_h_2")
        self.line_h_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_h_4.setGeometry(QtCore.QRect(5, 80, 193, 20))
        self.line_h_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h_4.setObjectName("line_h_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 180, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line_h_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_h_5.setGeometry(QtCore.QRect(3, 160, 221, 20))
        self.line_h_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h_5.setObjectName("line_h_5")
        self.input_thresh = QtWidgets.QSpinBox(self.centralwidget)
        self.input_thresh.setGeometry(QtCore.QRect(30, 210, 171, 24))
        self.input_thresh.setMinimum(-99)
        self.input_thresh.setProperty("value", -16)
        self.input_thresh.setObjectName("input_thresh")
        self.button_convert = QtWidgets.QPushButton(self.centralwidget)
        self.button_convert.setGeometry(QtCore.QRect(10, 720, 181, 32))
        self.button_convert.setObjectName("button_convert")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MSE Automatic Pause Cutter"))
        self.button_select_input.setText(_translate("MainWindow", "Выбор исходного файла"))
        self.input_min_length.setSuffix(_translate("MainWindow", " мс"))
        self.label.setText(_translate("MainWindow", "Установка параметров"))
        self.label_2.setText(_translate("MainWindow", "Минимальная длина паузы"))
        self.label_3.setText(_translate("MainWindow", "Минимальный порог"))
        self.input_thresh.setSuffix(_translate("MainWindow", " Дб"))
        self.button_convert.setText(_translate("MainWindow", "Преобразовать"))

from video_player import VideoPlayer
